### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by robmarkcole** [h2oai/cvpr-multiearth-deforestation-segmentation#2]
Hi, would you consider publishing the model weights?
Many thanks

**Comment by gaborfodor** [comment]
Hi @robmarkcole
Here is one of the latest checkpoints for the deforestation model:

https://0xdata-public.s3.amazonaws.com/beluga/wildfire/models/forest_ws2_60d_r8_all.pth

You will need to apply all the same preprocessing steps according to the config to make it work. 
Please also note that the competition was focusing on a small area in the amazon rainforest. The model might not generalize well to different regions.

**Comment by robmarkcole** [comment]
Many thanks @gaborfodor 
The preprocessing is [shown in this file](https://github.com/h2oai/cvpr-multiearth-deforestation-segmentation/blob/master/src/configs/forest_ws2_60d_r8_all.py) in a format I am not familiar with - are all bands from the 3 sensors used?

**Comment by gaborfodor** [comment]
Yes, all the bands listed in `BAND_LIMITS` are used.

The actual input tensors are created in the dataset class (based on the config ofc):
https://github.com/h2oai/cvpr-multiearth-deforestation-segmentation/blob/master/src/datasets/forest_dataset.py

**Comment by robmarkcole** [comment]
Right and is the file `balanced_lat_lons_v2.csv` somehow linking up the images from the different sensors and the deforestation mask?

**Comment by gaborfodor** [comment]
The training area had large blocks without any deforestation. It was easy to overfit on that area but it only improved the validation score. Such regions were downsampled for faster training and better train-test performance correlation.

`balanced_lat_lons_v2.csv` has the list of downsampled lat-lon tiles that were used to train the models.

**Comment by robmarkcole** [comment]
Great thanks for the info!
